# Run tInstall on Ubuntu against Python 3.8

name: Test R2020b and R2021a

on:
  push:
    branches:
      - R2020b
      - R2021a
      - main
  
  pull_request:
      - R2020b
      - R2021a
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-python-engine:
    strategy:
      matrix:
        matlab: [R2020b, R2021a]
    
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3.1.3
        with:
           python-version: 3.8
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
           release: ${{ matrix.matlab }}

      - uses: actions/checkout@v3

      - name: Run tests
        uses: matlab-actions/run-tests@v1
